language: python

matrix:
    fast_finish: true
    include:
        - os: linux
          dist: trusty
          sudo: required
          python: 3.5
          env: PYVERSION="3"
        - os: linux
          dist: trusty
          sudo: required
          python: 2.7
          env: PYVERSION=""

install:
    - sudo apt-get update
    - sudo apt-get install cython python${PYVERSION}-dev
    - pip${PYVERSION} install --upgrade pip setuptools wheel
    - pip${PYVERSION} install cython
    - pip${PYVERSION} install coveralls codecov pyflakes
    - pip${PYVERSION} install --only-binary=numpy,scipy scipy
    - pip${PYVERSION} install pycontracts Pillow

script:
  - make
  - python${PYVERSION} TMQI.py
  - python${PYVERSION} TMQI.py test.png test_ldr.png -g -t png | tee gray1.txt
  - python${PYVERSION} TMQI.py test.png test_ldr.png  -t png | tee color1.txt
  - python${PYVERSION} TMQI.py test.float32 test_ldr.float32 -i float32 -W 396 -H 561 -g | tee gray2.txt
  - python${PYVERSION} TMQI.py rgb_test.float32 rgb_test_ldr.float32 -i float32 -W 396 -H 561

  - diff -q gray1.txt
  - diff -q gray2.txt

after_success:
  - coveralls
