language: python

matrix:
    fast_finish: true
    include:
        - os: linux
          dist: trusty
          sudo: required
          python: 3.5
          env: PYVERSION="3"
        - os: linux
          dist: trusty
          sudo: required
          python: 2.7
          env: PYVERSION=""

install:
    - sudo apt-get update
    - sudo apt-get install cython python${PYVERSION}-dev
    - pip${PYVERSION} install --upgrade pip setuptools wheel
    - pip${PYVERSION} install cython
    - pip${PYVERSION} install coveralls codecov pyflakes
    - pip${PYVERSION} install --only-binary=numpy,scipy scipy
    - pip${PYVERSION} install -r requirements.txt

script:
  - make test

after_success:
  - coveralls
  - codecov