environment:
  matrix:
    - PYTHON: "C:\\Python27"
      MINICONDA: "C:\\Miniconda"
    - PYTHON: "C:\\Python34"
      MINICONDA: "C:\\Miniconda34"
    - PYTHON: "C:\\Python35"
      MINICONDA: "C:\\Miniconda35"
    - PYTHON: "C:\\Python36"
      MINICONDA: "C:\\Miniconda36"

install:
install:
    - "git clone --depth 1 git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"
    - "conda install numpy scipy scikit-image"

build: off

test_script:
  - wintest.bat

