environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install -U pip"
  - "pip install wheel"
  - "pip install --only-binary=numpy,scipy,scikit-image scikit-image numpy scipy"
  - "pip install coverage coveralls"
  - "pip install -r requirements-win.txt"

build: off

test_script:
  - wintest.bat
