environment:
  matrix:
    - PYTHON: "C:\\Python27"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python35"
    - PYTHON: "C:\\Python36"

install:
  - "%PYTHON%\\python.exe -m pip install --only-binary=numpy,scipy numpy scipy"
  - "%PYTHON%\\python.exe -m pip install wheel coverage coveralls"
  - "%PYTHON%\\python.exe -m pip install -r requirements-win.txt"

build: off

test_script:
  - wintest.bat
